#!/usr/bin/env bash

source /etc/mysqld-bootstrap.conf

readonly MYSQLD_SAFE=/usr/bin/mysqld_safe
readonly NICE=/bin/nice
readonly NICENESS="${MYSQL_NICENESS:-10}"
readonly PID_PATH=/var/run/mysqld/mysqld.pid
readonly PID_PROXY=/usr/bin/pidproxy

while true; do
	sleep 0.1
	[[ -e /var/lock/subsys/mysqld-bootstrap.lock ]] || break
done

exec ${NICE} \
	-n ${NICENESS} \
	${PID_PROXY} \
	${PID_PATH} \
	${MYSQLD_SAFE}
