#!/usr/bin/env bash

set -e

function __cleanup ()
{
	__delete_lock
}

function __create_lock ()
{
	if [[ -n ${lock_file} ]]
	then
		touch "${lock_file}"
	fi
}

function __delete_lock ()
{
	if [[ -f ${lock_file} ]]
	then
		rm -f "${lock_file}"
	fi
}

function __get_mysql_init_limit ()
{
	local -r default_value="${1:-60}"

	local value="${MYSQL_INIT_LIMIT}"

	if ! __is_valid_mysql_init_limit "${value}"
	then
		value="${default_value}"
	fi

	printf -- '%s' "${value}"
}

function __get_options ()
{
	local -r options="${1}"
	local -r pid_file="/var/run/mysqld/mysqld.pid"

	printf -- \
		'--pid-file=%s%s%s' \
		"${pid_file}" \
		"${options:+" "}" \
		"${options}"
}

function __is_valid_mysql_init_limit ()
{
	local -r non_zero_integer='^[1-9][0-9]*$'
	local -r value="${1}"

	if [[ ${value} =~ ${non_zero_integer} ]]
	then
		return 0
	fi

	return 1
}

function main ()
{
	local -r bin="/usr/sbin/mysqld"
	local -r bootstrap_state_file="/var/lib/misc/mysqld-bootstrap"
	local -r bootstrap_timeout="$((
		$(__get_mysql_init_limit) + 10
	))"
	local -r lock_file="/var/lock/subsys/mysqld-wrapper"
	local -r nice="/bin/nice"
	local -r niceness="10"

	local options
	local verbose="false"

	while [[ "${#}" -gt 0 ]]
	do
		case "${1}" in
			-v|--verbose)
				verbose="true"
				shift 1
				;;
		esac
	done

	if [[ -f ${lock_file} ]]
	then
		>&2 printf -- \
			'ERROR: %s lock detected - aborting\n' \
			"${0##*/}"
		exit 1
	fi

	trap __cleanup \
		EXIT INT TERM
	__create_lock

	options="$(
		__get_options
	)"

	if [[ ${verbose} == true ]]
	then
		printf -- \
			'INFO: %s waiting on %s\n' \
			"${0##*/}" \
			"${bootstrap_state_file##*/}"
	fi

	set +e
	until [[ -f ${bootstrap_state_file} ]]
	do
		if ! inotifywait -qq \
			-e "create" \
			-t "${bootstrap_timeout}" \
			"${bootstrap_state_file%/*}"
		then
			break
		fi
	done
	set -e

	if ! [[ -f ${bootstrap_state_file} ]]
	then
		>&2 printf -- \
			'ERROR: %s timed out waiting on %s\n' \
			"${0##*/}" \
			"${bootstrap_state_file##*/}"
		exit 1
	fi

	if [[ ${verbose} == true ]]
	then
		printf -- \
			'INFO: %s starting %s\n' \
			"${0##*/}" \
			"${bin##*/}"
	fi

	__cleanup
	trap - \
		EXIT INT TERM

	exec ${nice} \
		-n ${niceness} \
		${bin} \
		${options}
}

main "${@}"