
# Common parameters of create and run targets
define DOCKER_CONTAINER_PARAMETERS
--name $(DOCKER_NAME) \
--restart $(DOCKER_RESTART_POLICY) \
--env "MYSQL_AUTOSTART_MYSQLD_BOOTSTRAP=$(MYSQL_AUTOSTART_MYSQLD_BOOTSTRAP)" \
--env "MYSQL_AUTOSTART_MYSQLD_WRAPPER=$(MYSQL_AUTOSTART_MYSQLD_WRAPPER)" \
--env "MYSQL_ROOT_PASSWORD=$(MYSQL_ROOT_PASSWORD)" \
--env "MYSQL_ROOT_PASSWORD_HASHED=$(MYSQL_ROOT_PASSWORD_HASHED)" \
--env "MYSQL_SUBNET=$(MYSQL_SUBNET)" \
--env "MYSQL_USER=$(MYSQL_USER)" \
--env "MYSQL_USER_DATABASE=$(MYSQL_USER_DATABASE)" \
--env "MYSQL_USER_PASSWORD=$(MYSQL_USER_PASSWORD)" \
--env "MYSQL_USER_PASSWORD_HASHED=$(MYSQL_USER_PASSWORD_HASHED)"
endef

DOCKER_PUBLISH := $(shell \
	if [[ $(DOCKER_PORT_MAP_TCP_3306) != NULL ]]; then printf -- '--publish %s:3306\n' $(DOCKER_PORT_MAP_TCP_3306); fi; \
)
