
-- 
-- CREATE USER '%MYSQL_USER%'@'%MYSQL_USER_HOST%' IDENTIFIED BY '%MYSQL_USER_PASSWORD%';
-- GRANT ALL PRIVILEGES ON `%MYSQL_USER_DATABASE%`.* TO '%MYSQL_USER%'@'%MYSQL_USER_HOST%';

-- GRANT ALL PRIVILEGES ON `%MYSQL_USER_DATABASE%`.* TO '%MYSQL_USER%'@'%MYSQL_USER_HOST%' IDENTIFIED BY '%MYSQL_USER_PASSWORD%';